# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fav-movies-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-fav-movies
  template:
    metadata:
      labels:
        app: my-fav-movies
    spec:
      containers:
        - name: my-fav-movies
          image: my-fav-movies:latest
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80   
            - name: ConnectionStrings__DefaultConnection
              value: "Host=db-service; Port=5432; Database=myfavapp; Username=postgres; Password=postgres"

---

# Cluster IP Service
apiVersion: v1
kind: Service
metadata:
  name: my-fav-movies-service
spec:
  type: NodePort
  selector:
    app: my-fav-movies
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
